#!/usr/bin/python3
raise TypeError("Exception has been raised")